# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-30 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeGroupManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hgp_functional_group', models.CharField(choices=[('English', 'English'), ('Chinese', 'Chinese'), ('Hokkien', 'Hokkien'), ('Cantonese', 'Cantonese'), ('Indian', 'Indian'), ('Filipino', 'Filipino'), ('All', 'All')], max_length=25)),
                ('hgp_manager_name', models.CharField(max_length=50)),
                ('added', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
