# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-29 15:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpDeskManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hdmgr_functional_group', models.CharField(choices=[('Servicedesk', 'Servicedesk'), ('IT', 'IT'), ('Finance', 'Finance'), ('HR', 'HR')], max_length=25)),
                ('hdmgr_functional_group_area', models.CharField(max_length=75)),
                ('hdmgr_ticket_manager_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_number', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_category', models.CharField(choices=[('IT', 'IT'), ('Others', 'Others')], max_length=50)),
                ('ticket_issue', models.CharField(blank=True, max_length=100, null=True)),
                ('ticket_priority', models.CharField(choices=[('Super Urgent', 'Super Urgent'), ('Urgent', 'Urgent'), ('Normal', 'Normal')], default='Normal', max_length=25)),
                ('ticket_status', models.CharField(choices=[('Started', 'Started'), ('In Progress', 'In Progress'), ('Pending', 'Pending'), ('Completed', 'Completed'), ('Closed', 'Closed')], default='Started', max_length=25)),
                ('ticket_description', models.TextField(blank=True)),
                ('ticket_screenshot', models.FileField(blank=True, null=True, upload_to='helpdesk_snapshots/')),
                ('consent_manager_name', models.CharField(blank=True, max_length=20, null=True)),
                ('consent_manager_signed', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('', '')], default='', max_length=25)),
                ('consent_manager_reason', models.TextField(blank=True, null=True)),
                ('first_create_date', models.DateField(auto_now_add=True)),
                ('last_modified_date', models.DateField(auto_now=True)),
                ('ticket_edited_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_manager', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='helpdesk.HelpDeskManager')),
                ('consent_manager_key', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userapp.UserProfile')),
                ('ticket_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ticket_edited_on'],
            },
        ),
        migrations.CreateModel(
            name='TicketManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_manager_reply', models.TextField(blank=True)),
                ('first_create_date', models.DateField(auto_now_add=True)),
                ('last_modified_date', models.DateField(auto_now=True)),
                ('ticket_manager_edited_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('ticket_manager_fg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.HelpDeskManager')),
                ('ticket_manager_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket_manager_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.Ticket')),
            ],
        ),
    ]
