# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-01-01 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_auto_20171130_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='consent_manager_signed',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Keep it Pending', 'Keep it Pending'), ('Approval not required', 'Approval not required'), ('', '')], default='', max_length=25),
        ),
    ]
