# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-01-01 04:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20180101_1219'),
        ('helpdesk', '0003_auto_20180101_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='attach2project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Ldrproject'),
        ),
    ]
