# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-01-01 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0006_auto_20180101_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportadministrator',
            name='functional_group',
            field=models.CharField(choices=[('Marketing', 'Marketing'), ('CRM', 'CRM'), ('IT', 'IT'), ('HR', 'HR'), ('Finance', 'Finance'), ('Default', 'Default')], max_length=25),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='consent_manager_signed',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Keep it Pending', 'Keep it Pending'), ('Approval not required', 'Approval not required'), ('', '')], default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_category',
            field=models.CharField(choices=[('CRM', 'CRM'), ('IT', 'IT'), ('Others', 'Others')], max_length=50),
        ),
    ]
