# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-01-01 14:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpdesk', '0007_auto_20180101_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketResolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution_admin_reply', models.TextField(blank=True)),
                ('first_create_date', models.DateField(auto_now_add=True)),
                ('last_modified_date', models.DateField(auto_now=True)),
                ('resolution_admin_edited_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolution_admin_fg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.SupportAdministrator')),
                ('resolution_admin_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='consent_manager_signed',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Keep it Pending', 'Keep it Pending'), ('Approval not required', 'Approval not required'), (' ', ' ')], default='', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='ticketresolution',
            name='resolution_admin_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.Ticket'),
        ),
    ]
