# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-01-18 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0008_auto_20180101_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='user_group',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
