# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-29 15:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import portal.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendoffriend', models.CharField(blank=True, max_length=150, null=True)),
                ('frnd_options', models.CharField(choices=[('Friend Request', 'Friend Request'), ('Accept Friend Request', 'Accept Friend Request'), ('Unfriend', 'Unfriend')], max_length=25)),
                ('requested_date', models.DateTimeField(auto_now=True, null=True)),
                ('frndoffrnd_options', models.CharField(choices=[('Friend Request', 'Friend Request'), ('Accept Friend Request', 'Accept Friend Request'), ('Unfriend', 'Unfriend')], max_length=25)),
                ('accepted_date', models.DateTimeField(auto_now=True, null=True)),
                ('friend', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm_functional_group', models.CharField(choices=[('English', 'English'), ('Chinese', 'Chinese'), ('Hokkien', 'Hokkien'), ('Cantonese', 'Cantonese'), ('Indian', 'Indian'), ('Filipino', 'Filipino'), ('All', 'All')], max_length=25)),
                ('pm_manager_name', models.CharField(max_length=50)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Mdm', 'Mdm'), ('Dr', 'Dr'), ('Past', 'Past'), ('Evan', 'Evan'), ('Prof', 'Prof'), ('Mast', 'Mast')], default='Mr', max_length=4)),
                ('firstname', models.CharField(blank=True, max_length=25)),
                ('lastname', models.CharField(blank=True, max_length=25)),
                ('usercover', models.FileField(blank=True, null=True, upload_to='uploads/profile_pictures/', validators=[portal.validators.validate_imagefile_extension])),
                ('usermobile', models.CharField(blank=True, max_length=15)),
                ('address_line1', models.CharField(blank=True, max_length=30)),
                ('address_line2', models.CharField(blank=True, max_length=30)),
                ('city_or_town', models.CharField(blank=True, max_length=30)),
                ('state_or_province', models.CharField(blank=True, max_length=30)),
                ('postal_code', models.CharField(blank=True, max_length=7)),
                ('country', models.CharField(blank=True, max_length=20)),
                ('dob', models.DateField(blank=True, default='1920-01-01')),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Separated', 'Separated')], max_length=10)),
                ('number_of_children', models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], null=True)),
                ('who_brought_you_here', models.CharField(blank=True, max_length=40)),
                ('whos_mobile_number', models.CharField(blank=True, max_length=15)),
                ('sunday_service', models.CharField(choices=[('English', 'English'), ('Chinese', 'Chinese'), ('Hokkien', 'Hokkien'), ('Cantonese', 'Cantonese'), ('Indian', 'Indian'), ('Filipino', 'Filipino'), ('All', 'All')], default='English', max_length=25)),
                ('expertise', models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Management', 'Management'), ('Music/Sound', 'Music/Sound'), ('IT', 'IT'), ('Designer', 'Designer'), ('Programmer', 'Programmer'), ('Volunteer', 'Volunteer'), ('Planner', 'Planner'), ('Other', 'Other')], max_length=15)),
                ('membership', models.CharField(blank=True, choices=[('Member', 'Member'), ('Regular', 'Regular'), ('Visitor', 'Visitor')], max_length=10)),
                ('is_leader', models.BooleanField(default=False)),
                ('manager_name', models.CharField(blank=True, max_length=20)),
                ('ticket_manager_name', models.CharField(default='ticketmanager', max_length=20)),
                ('manager_type', models.CharField(blank=True, choices=[('Legal Manager', 'Legal Manager'), ('Leader', 'Leader')], max_length=20)),
                ('age_group', models.CharField(blank=True, choices=[('Senior', 'Senior'), ('Adult', 'Adult'), ('Youth', 'Youth'), ('Junior', 'Junior')], max_length=10)),
                ('oikos', models.CharField(blank=True, choices=[('FAMILY OIKOS: BEDOK SOUTH AVENUE 3, Blk 161, #01-515, S(460161)', 'FAMILY OIKOS: BEDOK SOUTH AVENUE 3, Blk 161, #01-515, S(460161)'), ('FAMILY OIKOS: CHAI CHEE ROAD, Blk 1, S(461001)', 'FAMILY OIKOS: CHAI CHEE ROAD, Blk 1, S(461001)'), ('FAMILY OIKOS: CHAI CHEE ST Blk 51, #08-310, S(460051)', 'FAMILY OIKOS: CHAI CHEE ST Blk 51, #08-310, S(460051)'), ('FAMILY OIKOS: CHAI CHEE ST Blk 54, #11-881, S(460054)', 'FAMILY OIKOS: CHAI CHEE ST Blk 54, #11-881, S(460054)'), ('FAMILY OIKOS: CHAI CHEE ROAD, Blk 19, #05-322 S(461019)', 'FAMILY OIKOS: CHAI CHEE ROAD, Blk 19, #05-322 S(461019)'), ('FAMILY OIKOS: JALAN BANGSAWAN 67, S(457828)', 'FAMILY OIKOS: JALAN BANGSAWAN 67, S(457828)'), ('FAMILY OIKOS: JALAN DAMAI, Blk 662, #13-135, S(410662)', 'FAMILY OIKOS: JALAN DAMAI, Blk 662, #13-135, S(410662)'), ('FAMILY OIKOS: HAIG COURT, Blk 158 #14-04, S(438794)', 'FAMILY OIKOS: HAIG COURT, Blk 158 #14-04, S(438794)'), ('FAMILY OIKOS: LORONG MELAYU, 78C, S(416985)', 'FAMILY OIKOS: LORONG MELAYU, 78C, S(416985)'), ('FAMILY OIKOS: PASIR RIS ST 52 511, #15-131, S(510511) * 8:30pm', 'FAMILY OIKOS: PASIR RIS ST 52 511, #15-131, S(510511) * 8:30pm'), ('FAMILY OIKOS: BETHESDA CATHEDRAL Conference Room, 2nd Flr', 'FAMILY OIKOS: BETHESDA CATHEDRAL Conference Room, 2nd Flr'), ('FAMILY OIKOS: SENGKANG EAST WAY, Blk 122A, #08-53, S(541122)', 'FAMILY OIKOS: SENGKANG EAST WAY, Blk 122A, #08-53, S(541122)'), ('FAMILY OIKOS: 1 SIMEI ST 4, #09-08, Simei Green S(529861)', 'FAMILY OIKOS: 1 SIMEI ST 4, #09-08, Simei Green S(529861)'), ('FAMILY OIKOS: BETHESDA CATHEDRAL, Classroom 2, 2nd Flr (Friday, 10.30am)', 'FAMILY OIKOS: BETHESDA CATHEDRAL, Classroom 2, 2nd Flr (Friday, 10.30am)'), ('FAMILY OIKOS: SUNSET WAY, Blk 135, #06-08, S(597158)', 'FAMILY OIKOS: SUNSET WAY, Blk 135, #06-08, S(597158)'), ('FAMILY OIKOS: TAMPINES ST 24, Blk 230, #07-126, S(524230)', 'FAMILY OIKOS: TAMPINES ST 24, Blk 230, #07-126, S(524230)'), ('FAMILY OIKOS: BETHESDA CATHEDRAL, Classroom 5, 2nd Flr', 'FAMILY OIKOS: BETHESDA CATHEDRAL, Classroom 5, 2nd Flr'), ('FAMILY OIKOS: BETHESDA CATHEDRAL, Classroom 1, 2nd Flr', 'FAMILY OIKOS: BETHESDA CATHEDRAL, Classroom 1, 2nd Flr'), ('FAMILY OIKOS: BETHESDA CATHEDRAL, Classroom 2, 2nd Flr', 'FAMILY OIKOS: BETHESDA CATHEDRAL, Classroom 2, 2nd Flr'), ('FAMILY OIKOS: BETHESDA CATHEDRAL, Daniel Hall, 2nd Flr (Sunday, 12 pm)', 'FAMILY OIKOS: BETHESDA CATHEDRAL, Daniel Hall, 2nd Flr (Sunday, 12 pm)'), ('YOUNG ADULTS: 10 AIDA STREET, S(459330)', 'YOUNG ADULTS: 10 AIDA STREET, S(459330)'), ('YOUNG ADULTS: BETHESDA CATHEDRAL Joseph Hall, 4th Flr', 'YOUNG ADULTS: BETHESDA CATHEDRAL Joseph Hall, 4th Flr'), ('YOUTH OIKOS: TERTIARY BEDOK NORTH AVENUE 1, Blk 552, #03-492, S(460552)', 'YOUTH OIKOS: TERTIARY BEDOK NORTH AVENUE 1, Blk 552, #03-492, S(460552)'), ('YOUTH OIKOS: LOWER SEC GIRLS BETHESDA CATHEDRAL (Sunday, 9:30 am)', 'YOUTH OIKOS: LOWER SEC GIRLS BETHESDA CATHEDRAL (Sunday, 9:30 am)'), ('YOUTH OIKOS: LOWER SEC BOYS BETHESDA CATHEDRAL (Sunday, 9:30 am)', 'YOUTH OIKOS: LOWER SEC BOYS BETHESDA CATHEDRAL (Sunday, 9:30 am)'), ('YOUTH OIKOS: BEDOK GREEN SECONDARY SCHOOL (FRIDAY, 2PM)', 'YOUTH OIKOS: BEDOK GREEN SECONDARY SCHOOL (FRIDAY, 2PM)'), ('YOUTH OIKOS: UPPER SECONDARY BETHESDA CATHEDRAL (Sunday, 9:30 am)', 'YOUTH OIKOS: UPPER SECONDARY BETHESDA CATHEDRAL (Sunday, 9:30 am)'), ('None', 'None')], max_length=75)),
                ('oikos_role', models.CharField(blank=True, choices=[('Leader', 'Leader'), ('Member', 'Member')], max_length=10)),
                ('community_services', models.CharField(blank=True, choices=[('Community Lunch', 'Community Lunch'), ('Tuition Centre', 'Tuition Centre'), ('Prayer for the sick', 'Prayer for the sick'), ('Monday Yum Cha', 'Monday Yum Cha'), ('No', 'No')], max_length=25)),
                ('community_services_role', models.CharField(blank=True, choices=[('CS Volunteer', 'CS Volunteer'), ('CS Volunteer-Leader', 'CS Volunteer-Leader'), ('TC Volunteer', 'TC Volunteer'), ('TC Volunteer-Leader', 'TC Volunteer-Leader'), ('P4S Volunteer', 'P4S Volunteer'), ('P4S Volunteer-Leader', 'P4S Volunteer-Leader'), ('MYC Volunteer', 'MYC Volunteer'), ('MYC Volunteer-Leader', 'MYC Volunteer-Leader')], max_length=25)),
                ('usher_ministry', models.CharField(blank=True, choices=[('Traffic Warden', 'Traffic Warden'), ('Greeting Usherer', 'Greeting Usherer'), ('Holy Communion Serving', 'Holy Communion Serving'), ('Offerings Usherer', 'Offerings Usherer'), ('Altar Call Usherer', 'Altar Call Usherer'), ('No', 'No')], max_length=25)),
                ('usher_ministry_role', models.CharField(blank=True, choices=[('Traffic Warden-Volunteer', 'Traffic Warden-Volunteer'), ('Traffic Warden-Volunteer-Leader', 'Traffic Warden-Volunteer-Leader'), ('Greeting Usherer-Volunteer', 'Greeting Usherer-Volunteer'), ('Greeting Usherer-Volunteer-Leader', 'Greeting Usherer-Volunteer-Leader'), ('Holy Communion Serving-Usherer', 'Holy Communion Serving-Usherer'), ('Holy Communion Serving-Usherer-Leader', 'Holy Communion Serving-Usherer-Leader'), ('Offerings Usherer', 'Offerings Usherer'), ('Offerings Usherer-Leader', 'Offerings Usherer-Leader'), ('Altar Call Usherer', 'Altar Call Usherer'), ('Altar Call Usherer-Leader', 'Altar Call Usherer-Leader')], max_length=40)),
                ('worship_ministry', models.CharField(blank=True, choices=[('Vocals', 'Vocals'), ('Sound', 'Sound'), ('Visuals', 'Visuals'), ('Guitar', 'Guitar'), ('Keys', 'Keys'), ('Drums', 'Drums'), ('Strings', 'Strings'), ('No', 'No')], max_length=25)),
                ('worship_ministry_role', models.CharField(blank=True, choices=[('Worship Leader', 'Worship Leader'), ('Male Vocal', 'Male Vocal'), ('Female Vocal', 'Female Vocal'), ('Lead Guitar', 'Lead Guitar'), ('Bass Guitar', 'Bass Guitar'), ('Rythm Guitar', 'Rythm Guitar'), ('Sound System', 'Sound System'), ('Visuals & Systems', 'Visuals & Systems'), ('Keys', 'Keys'), ('Strings', 'Strings'), ('Drums', 'Drums'), ('Inst. Maintenance', 'Inst. Maintenance')], max_length=25)),
                ('worship_ministry_team', models.CharField(blank=True, choices=[('Team-1', 'Team-1'), ('Team-2', 'Team-2'), ('Team-3', 'Team-3'), ('Team-4', 'Team-4'), ('Team-5', 'Team-5'), ('Team-6', 'Team-6')], max_length=25)),
                ('creative_media', models.CharField(blank=True, choices=[('Actor', 'Actor'), ('Actress', 'Actress'), ('Camera', 'Camera'), ('Director', 'Director'), ('Screen Play', 'Screen Play'), ('Costumes', 'Costumes'), ('Music', 'Music'), ('Editor', 'Editor'), ('Choreographer', 'Choreographer'), ('Mentor', 'Mentor'), ('Production', 'Production'), ('No', 'No')], max_length=25)),
                ('creative_media_role', models.CharField(blank=True, choices=[('Actor', 'Actor'), ('Actress', 'Actress'), ('Camera', 'Camera'), ('Director', 'Director'), ('Asst. Director', 'Asst. Director'), ('Screen Play Writer', 'Screen Play Writer'), ('Costumes', 'Costumes'), ('Music', 'Music'), ('Editor', 'Editor'), ('Choreographer', 'Choreographer'), ('Mentor', 'Mentor'), ('Production', 'Production')], max_length=25)),
                ('creative_media_team', models.CharField(blank=True, choices=[('Team-1', 'Team-1'), ('Team-2', 'Team-2'), ('Team-3', 'Team-3'), ('Team-4', 'Team-4'), ('Team-5', 'Team-5'), ('Team-6', 'Team-6')], max_length=25)),
                ('outreach_ministry', models.CharField(blank=True, choices=[('Make a difference day', 'Make a difference day'), ('Health Screenings', 'Health Screenings'), ('Financial peace courses', 'Financial peace courses'), ('Basics of Christian Living', 'Basics of Christian Living'), ('Pre-Marital Counselling', 'Pre-Marital Counselling'), ('Homebound Ministry', 'Homebound Ministry'), ('Computer Training', 'Computer Training'), ('Music Classes', 'Music Classes'), ('No', 'No')], max_length=25)),
                ('outreach_ministry_role', models.CharField(blank=True, choices=[('MADD -Outreach Champion', 'MADD -Outreach Champion'), ('MADD -Outreach Leader', 'MADD -Outreach Leader'), ('HS -Outreach Champion', 'HS -Outreach Champion'), ('HS -Outreach Leader', 'HS -Outreach Leader'), ('FPS -Outreach Champion', 'FPS -Outreach Champion'), ('FPS -Outreach Leader', 'FPS -Outreach Leader'), ('BOCL -Outreach Champion', 'BOCL -Outreach Champion'), ('BOCL -Outreach Leader', 'BOCL -Outreach Leader'), ('PMC -Outreach Champion', 'PMC -Outreach Champion'), ('PMC -Outreach Leader', 'PMC -Outreach Leader'), ('HM -Outreach Champion', 'HM -Outreach Champion'), ('HM -Outreach Leader', 'HM -Outreach Leader'), ('CT -Outreach Champion', 'CT -Outreach Champion'), ('CT -Outreach Leader', 'CT -Outreach Leader'), ('MC -Outreach Champion', 'MC -Outreach Champion'), ('MC -Outreach Leader', 'MC -Outreach Leader')], max_length=25)),
                ('outreach_ministry_team', models.CharField(blank=True, choices=[('Team-1', 'Team-1'), ('Team-2', 'Team-2'), ('Team-3', 'Team-3'), ('Team-4', 'Team-4'), ('Team-5', 'Team-5'), ('Team-6', 'Team-6')], max_length=25)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
