# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-30 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age_group',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='community_services',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='community_services_role',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='creative_media',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='creative_media_role',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='creative_media_team',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='expertise',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='number_of_children',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='oikos',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='oikos_role',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='outreach_ministry',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='outreach_ministry_role',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='outreach_ministry_team',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sunday_service',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='usher_ministry',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='usher_ministry_role',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='who_brought_you_here',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='whos_mobile_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='worship_ministry',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='worship_ministry_role',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='worship_ministry_team',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='manager_type',
            field=models.CharField(blank=True, choices=[('Legal Manager', 'Legal Manager'), ('Team Leader', 'Team Leader')], max_length=20),
        ),
    ]
