# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-01-15 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_auto_20171130_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('Internal', 'Internal'), ('External', 'External'), ('Intern', 'Intern')], default='External', max_length=20),
        ),
    ]
