# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-01-15 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_userprofile_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='city_or_town',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='salutation',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='state_or_province',
        ),
    ]
