# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-01-18 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_usergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_group',
            field=models.CharField(choices=[('None', 'None'), ('NCSS', 'NCSS')], default='None', max_length=20),
        ),
    ]
