# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-01-18 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_userprofile_user_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserGroup',
        ),
    ]
