# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-01-01 02:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ldrproject',
            fields=[
                ('projectId', models.AutoField(primary_key=True, serialize=False)),
                ('projectName', models.CharField(blank=True, max_length=100, null=True)),
                ('plannedStartDate', models.DateField(blank=True, null=True)),
                ('plannedEndDate', models.DateField(blank=True, null=True)),
                ('projectStartDate', models.DateField(blank=True, null=True)),
                ('projectEndDate', models.DateField(blank=True, null=True)),
                ('projectStatus', models.CharField(choices=[('Planned', 'Planned'), ('KickOff', 'KickOff'), ('Planning', 'Planning'), ('Realization', 'Realization'), ('FinalPreparation', 'FinalPreparation'), ('Live', 'Live'), ('Closing', 'Closing'), ('SignOff', 'SignOff'), ('Completed', 'Completed'), ('Pending', 'Pending'), ('Paused', 'Paused'), ('Suspended', 'Suspended'), ('', '')], default='', max_length=10)),
                ('projectType', models.CharField(choices=[('Pilot', 'Pilot'), ('New', 'New'), ('Enhancement', 'Enhancement'), ('Internal', 'Internal'), ('Support', 'Support')], default='', max_length=10)),
                ('projectDescription', models.TextField(blank=True)),
                ('firstCreateDate', models.DateField(auto_now_add=True)),
                ('projectEditedOn', models.DateTimeField(default=django.utils.timezone.now)),
                ('projectManager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-projectEditedOn'],
            },
        ),
        migrations.CreateModel(
            name='Ldrprojectschedule',
            fields=[
                ('scheduleID', models.AutoField(primary_key=True, serialize=False)),
                ('scheduleOrder', models.IntegerField()),
                ('workPackageName', models.TextField(blank=True)),
                ('hoursPerDay', models.IntegerField()),
                ('numberOfDays', models.IntegerField(blank=True, null=True)),
                ('workpackageType', models.CharField(choices=[('Activity', 'Activity'), ('Milestone', 'Milestone'), ('NoWorkDay', 'NoWorkDay'), ('', '')], default='', max_length=15)),
                ('scheduleStartDate', models.DateField(blank=True, null=True)),
                ('scheduleEndDate', models.DateField(blank=True, null=True)),
                ('firstCreateDate', models.DateField(auto_now_add=True)),
                ('scheduleEditedOn', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['scheduleOrder'],
            },
        ),
        migrations.CreateModel(
            name='Ldrresource',
            fields=[
                ('resourceID', models.AutoField(primary_key=True, serialize=False)),
                ('resourceOrder', models.IntegerField()),
                ('resourceName', models.CharField(max_length=25)),
                ('resourceRole', models.CharField(choices=[('Program Manager', 'Program Manager'), ('Project Manager', 'Project Manager'), ('Project Coordinator', 'Project Coordinator'), ('Asst Project Manager', 'Asst Project Manager'), ('Change Manager', 'Change Manager'), ('Risk Manager', 'Risk Manager'), ('Quality Manager', 'Quality Manager'), ('Team Lead1 Developer', 'Team Lead Developer'), ('Team Lead2 Developer', 'Team Lead2 Developer'), ('UX Designer', 'UX Designer'), ('UX&UI Designer', 'UX&UI Designer'), ('FE Developer', 'FE Developer'), ('BE Developer', 'BE Developer'), ('Infrastructure and Cloud', 'Infrastructure & Cloud'), ('IOS Developer', 'IOS Developer'), ('Android Developer', 'Android Developer'), ('App Developer', 'App Developer'), ('Content Developer', 'Content Developer'), ('AR Developer', 'AR Developer'), ('Trials Developer', 'Trials Developer'), ('', '')], default='', max_length=25)),
                ('resourceDescription', models.TextField(blank=True)),
                ('firstCreateDate', models.DateField(auto_now_add=True)),
                ('resourceEditedOn', models.DateTimeField(default=django.utils.timezone.now)),
                ('resourceManager', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('resourceToProject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Ldrproject')),
            ],
            options={
                'ordering': ['resourceOrder'],
            },
        ),
        migrations.CreateModel(
            name='Ldrscheduledactivity',
            fields=[
                ('activityID', models.AutoField(primary_key=True, serialize=False)),
                ('activityOrder', models.IntegerField()),
                ('avtivityName', models.TextField(blank=True)),
                ('numberOfDays', models.IntegerField(blank=True, null=True)),
                ('avtivityStartDate', models.DateField(blank=True, null=True)),
                ('avtivityEndDate', models.DateField(blank=True, null=True)),
                ('firstCreateDate', models.DateField(auto_now_add=True)),
                ('avtivityEditedOn', models.DateTimeField(default=django.utils.timezone.now)),
                ('avtivityManager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('scheduleName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Ldrprojectschedule')),
            ],
            options={
                'ordering': ['activityOrder'],
            },
        ),
        migrations.AddField(
            model_name='ldrprojectschedule',
            name='members',
            field=models.ManyToManyField(to='project.Ldrresource'),
        ),
        migrations.AddField(
            model_name='ldrprojectschedule',
            name='projectName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Ldrproject'),
        ),
        migrations.AddField(
            model_name='ldrprojectschedule',
            name='scheduleManager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
