# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-01-01 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldrproject',
            name='projectStatus',
            field=models.CharField(choices=[('Planned', 'Planned'), ('KickOff', 'KickOff'), ('Planning', 'Planning'), ('Realization', 'Realization'), ('FinalPreparation', 'FinalPreparation'), ('Live', 'Live'), ('Closing', 'Closing'), ('SignOff', 'SignOff'), ('Completed', 'Completed'), ('Pending', 'Pending'), ('Paused', 'Paused'), ('Suspended', 'Suspended'), ('', '')], default='', max_length=15),
        ),
    ]
