# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-01-01 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20180101_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldrproject',
            name='projectStatus',
            field=models.CharField(choices=[('Planned', 'Planned'), ('KickOff', 'KickOff'), ('Planning', 'Planning'), ('Realization', 'Realization'), ('FinalPreparation', 'FinalPreparation'), ('Live', 'Live'), ('Closing', 'Closing'), ('SignOff', 'SignOff'), ('Completed', 'Completed'), ('Pending', 'Pending'), ('Paused', 'Paused'), ('Suspended', 'Suspended'), ('', '')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='ldrproject',
            name='projectType',
            field=models.CharField(choices=[('Pilot', 'Pilot'), ('New', 'New'), ('Enhancement', 'Enhancement'), ('Internal', 'Internal'), ('Support', 'Support')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='ldrresource',
            name='resourceRole',
            field=models.CharField(choices=[('Program Manager', 'Program Manager'), ('Project Manager', 'Project Manager'), ('Project Coordinator', 'Project Coordinator'), ('Asst Project Manager', 'Asst Project Manager'), ('Change Manager', 'Change Manager'), ('Risk Manager', 'Risk Manager'), ('Quality Manager', 'Quality Manager'), ('Team Lead1 Developer', 'Team Lead Developer'), ('Team Lead2 Developer', 'Team Lead2 Developer'), ('UX Designer', 'UX Designer'), ('UX&UI Designer', 'UX&UI Designer'), ('FE Developer', 'FE Developer'), ('BE Developer', 'BE Developer'), ('Infrastructure and Cloud', 'Infrastructure & Cloud'), ('IOS Developer', 'IOS Developer'), ('Android Developer', 'Android Developer'), ('App Developer', 'App Developer'), ('Content Developer', 'Content Developer'), ('AR Developer', 'AR Developer'), ('Trials Developer', 'Trials Developer'), ('', '')], default='', max_length=30),
        ),
    ]
