# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-01-01 04:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20180101_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='projectRisk',
            fields=[
                ('riskID', models.AutoField(primary_key=True, serialize=False)),
                ('riskOrder', models.IntegerField()),
                ('riskFlag', models.CharField(choices=[('Green', 'Green'), ('Amber', 'Amber'), ('Red', 'Red'), ('Gray', 'Gray'), ('', '')], default='', max_length=25)),
                ('riskName', models.CharField(blank=True, max_length=50, null=True)),
                ('riskDescription', models.TextField(blank=True)),
                ('riskMitigation', models.TextField(blank=True)),
                ('mittigationStatus', models.CharField(choices=[('Identified', 'Identified'), ('Increased', 'Increased'), ('Decreased', 'Decreased'), ('On Focus', 'On Focus'), ('Under Control', 'Under Control'), ('Mittigated', 'Mittigated')], default='', max_length=25)),
                ('riskIdentifiedDate', models.DateField(blank=True, null=True)),
                ('riskMittigatedDate', models.DateField(blank=True, null=True)),
                ('firstCreateDate', models.DateField(auto_now_add=True)),
                ('riskEditedOn', models.DateTimeField(default=django.utils.timezone.now)),
                ('projectName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Ldrprojectschedule')),
            ],
            options={
                'ordering': ['riskOrder'],
            },
        ),
        migrations.AlterField(
            model_name='ldrresource',
            name='resourceRole',
            field=models.CharField(choices=[('Program Manager', 'Program Manager'), ('Project Manager', 'Project Manager'), ('Project Coordinator', 'Project Coordinator'), ('Asst Project Manager', 'Asst Project Manager'), ('Change Manager', 'Change Manager'), ('Risk Manager', 'Risk Manager'), ('Quality Manager', 'Quality Manager'), ('Team Lead1 Developer', 'Team Lead Developer'), ('Team Lead2 Developer', 'Team Lead2 Developer'), ('UX Designer', 'UX Designer'), ('UX&UI Designer', 'UX&UI Designer'), ('FE Developer', 'FE Developer'), ('BE Developer', 'BE Developer'), ('Infrastructure and Cloud', 'Infrastructure and Cloud'), ('IOS Developer', 'IOS Developer'), ('Android Developer', 'Android Developer'), ('App Developer', 'App Developer'), ('Content Developer', 'Content Developer'), ('AR Developer', 'AR Developer'), ('Trials Developer', 'Trials Developer'), ('', '')], default='', max_length=30),
        ),
    ]
