# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-01-03 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20180103_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrisk',
            name='riskweight',
            field=models.CharField(choices=[('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW')], default='', max_length=10),
        ),
    ]
