# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-01-07 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20180103_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldrresource',
            name='userId',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
