# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-01-07 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_ldrresource_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ldrscheduledactivity',
            old_name='avtivityEndDate',
            new_name='activityEndDate',
        ),
        migrations.RenameField(
            model_name='ldrscheduledactivity',
            old_name='avtivityManager',
            new_name='activityManager',
        ),
        migrations.RenameField(
            model_name='ldrscheduledactivity',
            old_name='avtivityName',
            new_name='activityName',
        ),
        migrations.RenameField(
            model_name='ldrscheduledactivity',
            old_name='avtivityStartDate',
            new_name='activityStartDate',
        ),
    ]
