# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-01-15 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20180107_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectManager',
            fields=[
                ('pmID', models.AutoField(primary_key=True, serialize=False)),
                ('pmUsername', models.CharField(max_length=40)),
                ('pmCreateDate', models.DateField(auto_now_add=True)),
                ('pmEditedOn', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
